const express = require('express')
const router = express.Router()
const UserController = require('../controller/user')
router.route("/users")
    .get(UserController.getAll)
    .post()
    .patch()
    .put()
    .delete()
module.exports = router